version: 2

updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "main"

  - package-ecosystem: "docker"
    directory: "/server"
    schedule:
      interval: "monthly"
    target-branch: "main"
    ignore:
      - dependency-name: python
        versions: ["3.9.x"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "main"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "main"

  - package-ecosystem: "pip"
    directory: "/server"
    schedule:
      interval: "monthly"
    target-branch: "main"
